name: leoBlogServer CI
# ci触发的条件
on:
  push: # 什么请求触发
    branches:
      - main # 作用在哪些分支上

jobs: # 构建的任务，一个工作流有多个构建任务，
  build-and-deploy:
    runs-on: ubuntu-latest # 在什么服务器上面执行这些任务，这里使用最新版本的ubuntu

    strategy:
      matrix:
        node-version: [16.x]

    steps: # 构建任务的步骤，一个任务可分为多个步骤
      # 步骤1 拉取仓库代码
      - name: Checkout # 步骤名称
        uses: actions/checkout@v2

      # 步骤2 给当前服务器安装node
      - name: use node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # 步骤3 下载项目依赖
      - name: install
        run: npm install

      # 将工作目录下的文件全部拷贝到部署服务器的工作目录
        scp: |
            ./* => /www/github-actions-express
        # 完成拷贝后在部署服务器执行的命令：进入项目目录，安装生产依赖，并使用 pm2 管理
        last_ssh: |
            cd /www/github-actions-express
            pm2 start dist/index.js
