name: leoBlogServer CI
# ci触发的条件
on:
  push: # 什么请求触发
    branches:
      - main # 作用在哪些分支上

jobs: # 构建的任务，一个工作流有多个构建任务，
  build-and-deploy:
    runs-on: ubuntu-latest # 在什么服务器上面执行这些任务，这里使用最新版本的ubuntu

    strategy:
      matrix:
        node-version: [16.x]

    steps: # 构建任务的步骤，一个任务可分为多个步骤
      # 步骤1 拉取仓库代码
      - name: Checkout # 步骤名称
        uses: actions/checkout@v2

      # 步骤2 给当前服务器安装node
      - name: use node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # 步骤3 下载项目依赖
      - name: install
        run: npm install

      # 步骤4 打包node项目
      - name: build
        run: tsc # 此处是你node项目的构建脚本

      - name: run project
        with:
          access_token: ${{ secrets.LEOBLOGSERVER }} 
        run: npm run start